
        // let start = 10;
        // let end = 100;

        // let num = Math.floor(Math.random(end-start)* 100)

        // // console.log(num)

        // let num =30;

        // if(num >=20 && num <=50) {
        //     console.log("Number is within range")
        // }
        // else {
        //     console.log("Number is not within range")
        // };

        let jan= 31, feb= 29, mar=31, apr= 30, may=31, jun=30, jul= 31, aug=31, sep=30, oct=31, nov=30, dec=31
        let month = nov
    
        
        if(month >=31) {
            console.log("This month has 31 or more days")
        }

        else if(month <= 29)  {
            console.log("This month is feburay")
        }

        else{
            console.log("This month has 30 or less days")
        };


        // let aPlus= 90-100, a= 85-89, aMinus= 80-84, bPlus= 75-79, b= 70-74, bMinus= 65-69, cPlus= 60-64, c= 55-59, cMinus= 50-54; 

        let grade= 74;

        if(grade >=90) {
            console.log("You got an A+")
        }

        else if( grade >=85 && grade <=89){
            console.log("You got an A")
        }

        else if (grade >=80 && grade <=84){
            console.log("You got an A-")
        }

        else if(grade >=75 && grade <=79) {
            console.log("You got an B+")
        }

        else if(grade >=70 && grade <=74){
            console.log("You got an B")
        }

        else if(grade >=65 && grade <=69){
            console.log("You got an B-")
        }

        else if(grade >=60 && grade <=64) {
            console.log("You got an C+")
        }

        else if(grade >=55 && grade <=59){
            console.log("You got an C")
        }

        else if(grade >=50 && grade <=54){
            console.log("You got an C-")
        }

        else {
            console.log("You have failed")
        };



        // let temperature = Math.floor(Math.random()*100); 

        // if(temperature <=30 || temperature >=70) {
        //     console.log(`Critical Temperature: ${temperature}°C`)
        // }

        // else {
        //     console.log(`Stable Temperature: ${temperature}°C`)
        // }; 



        // let check1 = true;
        // let check2 = true;
        // let check3 = false;
        // let check4 = true;

        // if ((check1 === true && check2 === true) && (check3 === true || check4 === true)) {
        //         console.log("Passed")
        // }
        
        // else {
        //         console.log("Failed")
        //     };
